FROM node:latest

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production --legacy-peer-deps

# Copy your source code and build the application
# (Assuming your source code is in the current directory)
COPY . ./
RUN npm run build

EXPOSE 80
CMD ["npm","run", "start"]
